stages:
  - build
  - test

default:
  image: maven:3.9.15-eclipse-temurin-17-alpine

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    paths:
      - target/*.jar

unit-test-job:
  stage: test
  script:
    - echo "Running tests and generating coverage report..."
    - mvn clean verify
  artifacts:
    paths:
      - target/site/jacoco/
  coverage: '/Total.*?([0-9]{1,3})%/'