server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: ${MAXFILESIZE:5MB}
      max-request-size: ${MAXREQUESTSIZE:10MB}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    baseline-version: 2

team:
  connect:
    storage:
      adapter:
        throw-if-not-configured: true
    calendarific:
      base-url: https://calendarific.com/api/v2
      api-key: ${CALENDARIFIC_API_KEY}
      update-on-startup: true